title: Reimagining Higher Education in a Climate Changed World
description: Exploring students' perspectives on Higher Education in the context of the climate crisis
baseurl: "" # DO NOT set this to anything for a user/org site
url: "https://heclimateperspectives.github.io"
markdown: kramdown
