title: Reimagining Higher Education
description: Exploring students' perspectives on Higher Education in the Context of the Climate Crisis
baseurl: "" # DO NOT set this to anything for a user/org site
url: "https://heclimateperspectives.github.io"
markdown: kramdown
